config/routes.rb
Rails.application.routes.draw do
  root to: "reminders#index"
  resources :reminders
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discord_messenger.rb
class DiscordMessenger
  def self.send(message, url)
    client = Discordrb::Webhooks::Client.new(url: url)
    client.execute do |builder|
      builder.content = message
    end
  end
end

app/models/interval_reminder.rb
class IntervalReminder < Reminder
  validates :interval_seconds, presence: true

  def remind
    DiscordMessenger.send(message, webhook_url)
    update(remind_at: remind_at + interval_seconds)
  end
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  validates :channel_name, presence: true
  validates :message,      presence: true
  validates :remind_at,    presence: true
  validates :type,         presence: true
  validates :webhook_url,  presence: true

  def self.remind
    reminders = Reminder.where(remind_at: (5.minutes.ago)..(5.minutes.since))
    reminders.each(&:remind)
  end

  def interval_days=(days)
    self.interval_seconds = days.blank? ? nil : days.to_i.days
  end

  def interval_days
    return if interval_seconds.nil?

    self.interval_seconds / 1.day
  end
end

app/models/spot_reminder.rb
class SpotReminder < Reminder
  validates :interval_seconds, absence: true

  def remind
    DiscordMessenger.send(message, webhook_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV['BASIC_AUTH_USER_NAME'], password: ENV['BASIC_AUTH_PASSWORD'] if Rails.env.production?
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: %i[ show edit update destroy ]

  # GET /reminders
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  def create
    @reminder = Reminder.new(reminder_params)
    if @reminder.save
      redirect_to @reminder.becomes(Reminder), notice: "Reminder was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /reminders/1
  def update
    @reminder = @reminder.becomes(reminder_params[:type].constantize)

    if @reminder.update(reminder_params)
      redirect_to @reminder.becomes(Reminder), notice: "Reminder was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /reminders/1
  def destroy
    @reminder.destroy
    redirect_to reminders_url, notice: "Reminder was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reminder_params
      params.require(:reminder).permit(:remind_at, :message, :interval_days, :type, :webhook_url, :channel_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReminderBot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reminders/_form.html.erb
<%= form_with(model: @reminder.becomes(Reminder)) do |form| %>
  <% if reminder.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
        <% reminder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :remind_at, style: "display: block" %>
    <%= form.datetime_field :remind_at, step: 600, required: true %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message, required: true %>
  </div>

  <% if @reminder.new_record? %>
    <div>
      <%= form.label :webhook_url, style: "display: block" %>
      <%= form.text_field :webhook_url, required: true %>
    </div>
  <% end %>

  <div>
    <%= form.label :channel_name, style: "display: block" %>
    <%= form.text_field :channel_name, required: true %>
  </div>

  <div>
    <%= form.label :interval_days, style: "display: block" %>
    <%= form.number_field :interval_days %>
  </div>

  <div>
    <%= form.label :type, style: "display: block" %>

    <%= form.collection_radio_buttons :type, %w[SpotReminder IntervalReminder], :to_s, :to_s, {}, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reminders/_reminder.html.erb
<div id="<%= dom_id reminder %>">
  <p>
    <strong>Remind at:</strong>
    <%= reminder.remind_at %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= reminder.message %>
  </p>

  <% if reminder.type == 'IntervalReminder' %>
    <p>
      <strong>Interval seconds:</strong>
      <%= reminder.interval_seconds %>
    </p>
  <% end %>

  <p>
    <strong>Type:</strong>
    <%= reminder.type %>
  </p>

</div>

app/views/reminders/edit.html.erb
<h1>Editing reminder</h1>

<%= render "form", reminder: @reminder %>

<br>

<div>
  <%= link_to "Show this reminder", @reminder.becomes(Reminder) %> |
  <%= link_to "Back to reminders", reminders_path %>
</div>

app/views/reminders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reminders</h1>

<div id="reminders">
  <% @reminders.each do |reminder| %>
    <%= render reminder.becomes(Reminder) %>
    <p>
      <%= link_to "Show this reminder", reminder.becomes(Reminder) %>
    </p>
  <% end %>
</div>

<%= link_to "New reminder", new_reminder_path %>

app/views/reminders/new.html.erb
<h1>New reminder</h1>

<%= render "form", reminder: @reminder %>

<br>

<div>
  <%= link_to "Back to reminders", reminders_path %>
</div>

app/views/reminders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reminder.becomes(Reminder) %>

<div>
  <%= link_to "Edit this reminder", edit_reminder_path(@reminder) %> |
  <%= link_to "Back to reminders", reminders_path %>

  <%= button_to "Destroy this reminder", @reminder.becomes(Reminder), method: :delete %>
</div>